[world]
name = "survivor_valhalla"
description = "Survivor Valhalla - Beast lineup management on Starknet"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/survivor-valhalla"
seed = "dojo_survivor_valhalla"
storage_snapshot_url = ""
version = "0.2.8"

[namespace]
default = "survivor_valhalla"

[env]
# rpc_url = ""         # env: STARKNET_RPC_URL
# account_address = "" # env: DOJO_ACCOUNT_ADDRESS
# private_key = ""     # env: DOJO_PRIVATE_KEY
world_address = "0x0506afd1468177a7d2de7a0d05f7675eea6cfdc081b41cb604f812ebb3cc4dc4"

[writers]
"survivor_valhalla" = ["survivor_valhalla-beast_actions", "survivor_valhalla-battle_actions", "survivor_valhalla-energy_actions"]
