[package]
cairo-version = "2.12.2"
name = "survivor_valhalla"
version = "1.7.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
spawn = "sozo execute survivor_valhalla-actions spawn --wait"
move = "sozo execute survivor_valhalla-actions move -c 1 --wait"

[dependencies]
dojo = "1.7.1"
starknet = "2.12.2"
beasts_nft = { git = "https://github.com/Provable-Games/beasts.git" }
openzeppelin_token = "1.0.0"

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "beasts_nft::beasts_nft"
    ]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.12.2"

[profile.mainnet]

[profile.sepolia]
