world_address = "0x0506afd1468177a7d2de7a0d05f7675eea6cfdc081b41cb604f812ebb3cc4dc4"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[indexing]
contracts = [
  "erc721:0x046da8955829adf2bda310099a0063451923f02e648cf25a1203aac6335cf0e4", # beasts
  "erc721:0x036017E69D21D6D8c13E266EaBB73ef1f1D02722D86BDcAbe5f168f8e549d3cD", # adventurers
]
[sql]
historical = [
  "survivor_valhalla-BeastLineupRegistered",
  "survivor_valhalla-BeastSwapped",
]
